version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.3
jobs:
  # cfn-lint:
  #   executor: aws-cli/default
  #   steps:
  #     # - aws-cli/setup:
  #     #     profile-name: default
  #     - checkout
  #     - run: pip install cfn-lint
  #     - run:
  #         name: run cfn-lint
  #         command: |
  #           cfn-lint -i W3002 -t cfn/*/*.yml
  tackcat-test:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          profile-name: default
      - checkout
      - run:
          name: install taskcat
          command: pip install taskcat
      - run:
          name: testing cfn deployment
          command: |
            cd cfn
            taskcat test run -m -d
          no_output_timeout: 30m #default 10m
  remove-test-bucket:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          profile-name: default
      - run:
          name: remove taskcat bucket
          command: aws s3 ls | awk '{print $3}' | grep "^tcat" | xargs -I {} aws s3 rb s3://{} --force

workflows:
  raisetech:
    jobs:
      # - cfn-lint:
      #     requires:
      #       - aws-cli-setup
      - tackcat-test
      - remove-test-bucket:
          requires:
            - tackcat-test
