version: 2.1
orbs:
  # python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@3.1.3
jobs:
  aws-cli-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          profile-name: default
  cfn-lint:
    executor: aws-cli/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cfn/*/*.yml
  tackcat-test:
    executor: aws-cli/default
    steps:
      - checkout
      - run: ls -la
      - run: pip install taskcat
      - run: taskcat test run -m

workflows:
  raisetech:
    jobs:
      - aws-cli-setup
      - cfn-lint:
          requires:
            - aws-cli-setup
      - tackcat-test:
          requires:
            - aws-cli-setup
