AWSTemplateFormatVersion: 2010-09-09
Description: |

Parameters:
  BaseName:
    Type: String
    Description: Base name for all resources
    Default: raisetech202210-cfn

Resources:
  CircleCiIpList:
    Type: AWS::EC2::PrefixList
    Properties:
      AddressFamily: "IPv4" # Required
      Entries:
        - Cidr: 3.228.39.90
        - Cidr: 18.213.67.41
        - Cidr: 34.194.94.201
        - Cidr: 34.194.144.202
        - Cidr: 34.197.6.234
        - Cidr: 35.169.17.173
        - Cidr: 35.174.253.146
        - Cidr: 52.3.128.216
        - Cidr: 52.4.195.249
        - Cidr: 52.5.58.121
        - Cidr: 52.21.153.129
        - Cidr: 52.72.72.233
        - Cidr: 54.92.235.88
        - Cidr: 54.161.182.76
        - Cidr: 54.164.161.41
        - Cidr: 54.166.105.113
        - Cidr: 54.167.72.230
        - Cidr: 54.172.26.132
        - Cidr: 54.205.138.102
        - Cidr: 54.208.72.234
        - Cidr: 54.209.115.53
      MaxEntries: 30 # Required
      PrefixListName: !Sub "${BaseName}-circleci-iplist" # Required
      Tags:
        - Key: Name
          Value: !Sub "${BaseName}-circleci-iplist"
  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "for EC2" # Required
      GroupName: !Sub "${BaseName}-ec2-sg"
      SecurityGroupIngress:
        - Description: "from ALB"
          FromPort: 80
          ToPort: 80
          IpProtocol: "tcp"
          SourceSecurityGroupId: !Ref AlbSecurityGroup
        - Description: "SSH from CircleCI"
          FromPort: 22
          ToPort: 22
          IpProtocol: "tcp"
          SourcePrefixListId: !Ref CircleCiIpList
      Tags:
        - Key: "Name"
          Value: !Sub "${BaseName}-ec2-sg"
      VpcId:
        Fn::ImportValue: !Sub "${BaseName}-VpcId"
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "for ALB" # Required
      GroupName: !Sub "${BaseName}-alb-sg"
      SecurityGroupIngress:
        - Description: "from ALB"
          FromPort: 80
          ToPort: 80
          IpProtocol: "tcp"
          CidrIp: "0.0.0.0/0"
      Tags:
        - Key: "Name"
          Value: !Sub "${BaseName}-alb-sg"
      VpcId:
        Fn::ImportValue: !Sub "${BaseName}-VpcId"
  RdsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "for RDS" # Required
      GroupName: !Sub "${BaseName}-rds-sg"
      SecurityGroupIngress:
        - Description: "from EC2"
          FromPort: 3306
          ToPort: 3306
          IpProtocol: "tcp"
          SourceSecurityGroupId: !Ref Ec2SecurityGroup
      Tags:
        - Key: "Name"
          Value: !Sub "${BaseName}-rds-sg"
      VpcId:
        Fn::ImportValue: !Sub "${BaseName}-VpcId"

Outputs:
  Ec2SecurityGroupId:
    Description: "EC2 Security Group ID"
    Value: !Ref Ec2SecurityGroup
    Export:
      Name: !Sub "${BaseName}-Ec2SecurityGroupId"
  AlbSecurityGroupId:
    Description: "ALB Security Group ID"
    Value: !Ref AlbSecurityGroup
    Export:
      Name: !Sub "${BaseName}-AlbSecurityGroupId"
  RdsSecurityGroupId:
    Description: "RDS Security Group ID"
    Value: !Ref RdsSecurityGroup
    Export:
      Name: !Sub "${BaseName}-RdsSecurityGroupId"
