general:
  s3_regional_buckets: true
project:
  name: raisetech202210
  regions:
    - ap-northeast-1
tests:
  root:
    template: ./root_stack.yml
    parameters:
      TemplateVPC: https://s3.amazonaws.com/$[taskcat_autobucket]/$[taskcat_project_name]/01_network/01_vpc.yml
      TemplateSG: https://s3.amazonaws.com/$[taskcat_autobucket]/$[taskcat_project_name]/01_network/02_sg.yml
      TemplateEC2: https://s3.amazonaws.com/$[taskcat_autobucket]/$[taskcat_project_name]/02_compute/01_ec2.yml
      TemplateRDS: https://s3.amazonaws.com/$[taskcat_autobucket]/$[taskcat_project_name]/02_compute/02_rds.yml
      TemplateALB: https://s3.amazonaws.com/$[taskcat_autobucket]/$[taskcat_project_name]/02_compute/03_alb.yml
      DbPassword: $[taskcat_genpass_8A]
