AWSTemplateFormatVersion: "2010-09-09"
Description: root stack template
Parameters:
  TemplateVPC:
    Description: VPC template URL(https://)
    Type: String
  TemplateSG:
    Description: SG template URL(https://)
    Type: String
  TemplateEC2:
    Description: EC2 template URL(https://)
    Type: String
  TemplateRDS:
    Description: RDS template URL(https://)
    Type: String
  TemplateALB:
    Description: ALB template URL(https://)
    Type: String
  DbPassword:
    Description: Password for RDS
    Type: String
    NoEcho: true
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateVPC
      Parameters:
        BaseName: raisetech202210-taskcat
  SG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateSG
      Parameters:
        BaseName: raisetech202210-taskcat
    DependsOn: VPC
  EC2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateEC2
      Parameters:
        BaseName: raisetech202210-taskcat
    DependsOn: SG
  RDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateRDS
      Parameters:
        BaseName: raisetech202210-taskcat
        DbPassword: !Ref DbPassword
    DependsOn: SG
  ALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateALB
      Parameters:
        BaseName: raisetech202210-taskcat
    DependsOn: EC2
