- name: rvm installed check
  stat: path=/home/{{ rails_user }}/.rvm/scripts/rvm
  register: rvm_installed
  become: yes
  become_user: "{{ rails_user }}"
  when: rails_user is defined

- name: install gpg keys
  shell: "gpg2 --keyserver hkp://keys.openpgp.org:80 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB"
  when: rvm_installed.stat.exists == false and rails_user is defined

- name: setup rvm
  shell: "curl -sSL https://get.rvm.io | bash -s stable"
  become: yes
  become_user: "{{ rails_user }}"
  args:
    creates: "/home/{{ rails_user }}/.rvm/scripts/rvm"
  when: rvm_installed.stat.exists == false and rails_user is defined
